name: polymer_dependency_injection
version: 0.0.6
author: Matthew Franglen <matthew.franglen@gmail.com>
homepage: https://github.com/matthewfranglen/dart-polymer-dependency-injection
description: Spring style annotation driven dependency injection with DOM scanning for autoconfiguration
dependencies:
  polymer: ">=0.14.0 <0.16.0"
  annotate: ">=0.0.1 <0.1.0"
  dependency_injection:
    git: git@github.com:matthewfranglen/dart-dependency-injection.git
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points:
      - example/index.html
      - test/test_polymer_dependency_injection.html
